### ISSUE TITLE
How to italicize the x or y axis labels on plot using ggplot2 

### ISSUE THREAD

**Issue by duttashi** [duttashi/visualize#51]
How to italicize the x or y axis label in ggplot2

**Comment by duttashi** [comment]
With `ggplot2` we can modify the axis title along the x or y-axis with `theme`. Use `element_text(face="italic")`. For more information, type `help (element_text)` in the R console.

```
library(ggplot2)
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point() +
  theme(axis.title.y = element_text(face = "italic"),
        axis.title.x = element_text(face = "italic"))
```

**Comment by macrotera** [comment]
this answer helps with axis title, not axis labels.
